# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.IntegerField(default=4)),
                ('customer_code', models.CharField(max_length=80)),
                ('app_key', models.CharField(max_length=80)),
                ('app_secret', models.CharField(max_length=80)),
                ('api_url', models.CharField(max_length=200)),
                ('simulation', models.IntegerField(default=0)),
                ('machine_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=80)),
                ('remark', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=80)),
                ('remark', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
