# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_scale',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(default=property, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_unit',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
