# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard2', '0002_auto_20170310_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='latest_value',
            field=models.IntegerField(default=15),
        ),
    ]
