# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard2', '0003_config_latest_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='latest_value',
            field=models.IntegerField(default=20),
        ),
    ]
