# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard2', '0004_auto_20170310_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
